# Generated by Django 4.1.5 on 2023-04-11 21:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0005_alter_brand_image_name_alter_product_image_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=10, unique=True, verbose_name='کد کوپن')),
                ('start_date', models.DateTimeField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(verbose_name='تاریخ پایان')),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='میزان تخفیف')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'کوپن تخفیف',
                'verbose_name_plural': 'کوپن های تخفیف',
                'db_table': 't_coupon',
            },
        ),
        migrations.CreateModel(
            name='DiscountBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_title', models.CharField(max_length=10, unique=True, verbose_name='عنوان سبد تخفیف')),
                ('start_date', models.DateTimeField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(verbose_name='تاریخ پایان')),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='میزان تخفیف')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'سبد تخفیف',
                'verbose_name_plural': 'سبدهای تخفیف',
                'db_table': 't_discount_basket',
            },
        ),
        migrations.CreateModel(
            name='DiscountBasketDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_basket_details1', to='discountsApp.discountbasket', verbose_name='سبد تخفیف')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_basket_details2', to='product.product', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'سبد تخفیف',
                'verbose_name_plural': 'سبدهای تخفیف',
                'db_table': 't_discount_basket_details',
            },
        ),
    ]
