# Generated by Django 4.1.5 on 2023-04-06 17:40

import apps.article.models
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='عنوان مقاله')),
                ('main_image_name', models.ImageField(upload_to=apps.article.models.main_image_blog_path, verbose_name='تصویر عکس اصلی')),
                ('short_text', models.TextField(verbose_name='متن خلاصه')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='متن اصلی')),
                ('key_words', models.CharField(blank=True, max_length=200, null=True, verbose_name='کلمات کلیدی')),
                ('register_date', models.DateField(auto_now_add=True, verbose_name='تاریخ درج مقاله')),
                ('is_active', models.BooleanField(verbose_name='وضعیت فعال/غیرفعال')),
                ('view_number', models.PositiveBigIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'db_table': 't_article',
            },
        ),
        migrations.CreateModel(
            name='ArticleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'گروه مقاله',
                'verbose_name_plural': 'گروه مقالات',
                'db_table': 't_article_group',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('family', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='ایمیل')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت فعال/غیرفعال')),
                ('slug', models.SlugField(blank=True, max_length=300, null=True, verbose_name='هنوان لاتین')),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسنده ها',
                'db_table': 't_blog_author',
            },
        ),
        migrations.CreateModel(
            name='ArticleGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.ImageField(upload_to=apps.article.models.gallery_image_path, verbose_name='تصویر')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_article', to='article.article', verbose_name='مقاله')),
            ],
            options={
                'verbose_name': 'گالری مقاله',
                'verbose_name_plural': 'گالری مقالات',
                'db_table': 't_article_gallery',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ManyToManyField(to='article.author', verbose_name='نویسنده'),
        ),
        migrations.AddField(
            model_name='article',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.articlegroup', verbose_name='گروه مقاله'),
        ),
    ]
