# Generated by Django 4.1.5 on 2023-04-11 20:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0004_alter_brand_image_name_alter_product_image_name_and_more'),
        ('accounts', '0003_alter_customer_image_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ درج')),
                ('update_date', models.DateField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('is_finaly', models.BooleanField(default=False, verbose_name='وضعیت سفارش')),
                ('order_code', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='کد تولیدی برای سفارش')),
                ('discount', models.IntegerField(blank=True, default=0, null=True, verbose_name='تخفیف روی فاکتور')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'db_table': 't_order',
            },
        ),
        migrations.CreateModel(
            name='OrderState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_state_title', models.CharField(max_length=100, verbose_name='وضعیت سفارش')),
            ],
            options={
                'verbose_name': 'وضعیت سفارش',
                'verbose_name_plural': 'وضعیت سفارش ها',
                'db_table': 't_order_state',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_title', models.CharField(max_length=50, verbose_name='نوع پرداخت')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'روش پرداخت',
                'db_table': 't_payment',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_detail1', to='orderApp.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_detail2', to='product.product', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'جزیئات سفارش',
                'verbose_name_plural': 'جزیئات سفارشات',
                'db_table': 't_orderdetails',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_state', to='orderApp.orderstate', verbose_name='وضعیت سفارش'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_types', to='orderApp.payment', verbose_name='نوع پرداخت'),
        ),
    ]
